services:
  portal:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9123:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - db
    networks:
      - sonarqube_network

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - sonarqube_network

  scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonarqube_scanner
    profiles: ["cli-only"]
    volumes:
      - ./sonar-project.properties:/usr/src/sonar-project.properties
      - /path/to/your/project:/usr/src
    networks:
      - sonarqube_network

volumes:
  sonarqube_db_data:

networks:
  sonarqube_network: